/**
 * Version Data
 * 
 * ⚠️ AUTO-GENERATED: This file is automatically generated from packages/beacon-ui/CHANGELOG.md
 * Do not edit manually. Run `npm run sync:version` to regenerate.
 */

export interface ChangeItem {
  description: string;
}

export interface VersionEntry {
  version: string;
  date: string;
  added?: ChangeItem[];
  changed?: ChangeItem[];
  fixed?: ChangeItem[];
  deprecated?: ChangeItem[];
  removed?: ChangeItem[];
  security?: ChangeItem[];
}

const versionData: VersionEntry[] = [
  {
    "version": "3.2.0",
    "date": "2025-01-01",
    "changed": [
      {
        "description": "Simplified Card component usage examples for better developer experience"
      },
      {
        "description": "Removed unnecessary wrapper divs from Card examples - Card's built-in flex layout handles spacing automatically"
      },
      {
        "description": "Improved code examples to be cleaner and more minimal, following design system best practices"
      },
      {
        "description": "Card examples now demonstrate cleaner, more maintainable code patterns"
      }
    ],
    "fixed": [
      {
        "description": "Fixed missing line-height in typography previews across Card component examples"
      },
      {
        "description": "Fixed image constraints in Product Card Pattern example - removed fixed width/height props for better flexibility"
      }
    ]
  },
  {
    "version": "3.1.9",
    "date": "2025-12-29",
    "added": [
      {
        "description": "Menu component now supports render props for full customization:"
      },
      {
        "description": "`renderSwitch` - Customize or replace the Switch component with your own implementation"
      },
      {
        "description": "`renderToggleButton` - Customize or replace the toggle button (menu/close icon) with your own component"
      },
      {
        "description": "`renderButton` - Customize or replace the menu action button with your own component"
      },
      {
        "description": "Menu component callback props for handling interactions:"
      },
      {
        "description": "`onSwitchChange` - Callback when Switch value changes"
      },
      {
        "description": "`onToggleButtonClick` - Callback when toggle button is clicked"
      },
      {
        "description": "`onButtonClick` - Callback when menu action button is clicked"
      },
      {
        "description": "Exported render prop types: `SwitchRenderProps`, `ToggleButtonRenderProps`, `MenuButtonRenderProps`"
      }
    ],
    "changed": [
      {
        "description": "Menu component now uses internal state management for Switch, allowing better control and customization"
      },
      {
        "description": "Render props are optional - if not provided, Menu uses default components (backward compatible)"
      }
    ]
  },
  {
    "version": "3.1.8",
    "date": "2025-12-29",
    "fixed": [
      {
        "description": "Button component now preserves variant colors (success, critical, warning) when in loading state"
      },
      {
        "description": "Previously, buttons would revert to default/primary color when loading was enabled"
      },
      {
        "description": "Loading state no longer overrides variant-specific colors"
      }
    ]
  },
  {
    "version": "3.1.7",
    "date": "2025-12-29",
    "changed": [
      {
        "description": "Menu component desktop variant now uses `height: \"100%\"` by default to fill container height instead of fixed `600px`"
      },
      {
        "description": "Custom height can still be set via the `style` prop to override the default behavior"
      }
    ]
  },
  {
    "version": "3.1.6",
    "date": "2025-12-29",
    "added": [
      {
        "description": "Optional `state` prop to Button component for controlled state management (default, hovered, focused, pressed)"
      },
      {
        "description": "Optional `status` prop to Switch, Checkbox, and RadioButton components for controlled state management"
      },
      {
        "description": "Components now support both controlled (via props) and uncontrolled (internal state) modes"
      },
      {
        "description": "Exported status/state types: `ButtonState`, `SwitchStatus`, `CheckboxStatus`, `RadioButtonStatus`"
      }
    ],
    "fixed": [
      {
        "description": "Menu component now uses public `Switch` component API instead of internal `SwitchPreview`"
      },
      {
        "description": "Menu component accepts optional `avatarImageUrl` prop instead of hardcoded image path"
      },
      {
        "description": "Menu component properly uses theme context for theme and hue values"
      },
      {
        "description": "Fixed nested button hydration error in Switch component wrapper"
      }
    ],
    "changed": [
      {
        "description": "Menu component falls back to `UserPersonIcon` when `avatarImageUrl` is not provided"
      },
      {
        "description": "Button, Switch, Checkbox, and RadioButton components now only update internal state when status/state prop is not provided (controlled pattern)"
      }
    ]
  },
  {
    "version": "3.1.5",
    "date": "2025-12-29",
    "fixed": [
      {
        "description": "Menu component now uses public `Switch` component API instead of internal `SwitchPreview`"
      },
      {
        "description": "Menu component accepts optional `avatarImageUrl` prop instead of hardcoded image path"
      },
      {
        "description": "Menu component properly uses theme context for theme and hue values"
      }
    ],
    "changed": [
      {
        "description": "Menu component falls back to `UserPersonIcon` when `avatarImageUrl` is not provided"
      }
    ]
  },
  {
    "version": "3.1.4",
    "date": "2025-12-29",
    "added": [
      {
        "description": "Initial npm package release as `beacon-ui`"
      },
      {
        "description": "README.md with installation and usage instructions"
      },
      {
        "description": "CHANGELOG.md for version tracking"
      },
      {
        "description": "Comprehensive documentation for all components"
      },
      {
        "description": "TypeScript type exports for design tokens"
      },
      {
        "description": "9 production-ready components:"
      },
      {
        "description": "Avatar"
      },
      {
        "description": "Button"
      },
      {
        "description": "Card"
      },
      {
        "description": "Checkbox"
      },
      {
        "description": "Chip"
      },
      {
        "description": "Input"
      },
      {
        "description": "Menu"
      },
      {
        "description": "Radio Button"
      },
      {
        "description": "Switch"
      },
      {
        "description": "ThemeProvider for theme and hue management"
      },
      {
        "description": "Complete design token system:"
      },
      {
        "description": "Primitives (colors, spacing, typography)"
      },
      {
        "description": "Semantic tokens (primary, success, warning, critical)"
      },
      {
        "description": "Brand tokens (light/dark themes)"
      },
      {
        "description": "Responsive tokens (desktop, tablet, mobile)"
      },
      {
        "description": "Effect tokens (shadows)"
      },
      {
        "description": "Typography tokens"
      },
      {
        "description": "TypeScript support with full type definitions"
      },
      {
        "description": "Icon component library"
      },
      {
        "description": "Support for multiple themes (light/dark)"
      },
      {
        "description": "Support for multiple hue variants (chromatic-prime, hue-sky, hue-indigo)"
      },
      {
        "description": "Token-driven architecture"
      },
      {
        "description": "WCAG 2.1 AA accessibility compliance"
      },
      {
        "description": "Responsive design support"
      },
      {
        "description": "Full TypeScript support"
      },
      {
        "description": "React 18 and 19 compatibility"
      }
    ]
  }
];

/**
 * Get all version entries (newest first)
 */
export function getVersionHistory(): VersionEntry[] {
  return versionData;
}

/**
 * Get the current (latest) version entry
 */
export function getCurrentVersion(): VersionEntry | null {
  return versionData.length > 0 ? versionData[0] : null;
}

/**
 * Get the previous version entry
 */
export function getPreviousVersion(): VersionEntry | null {
  return versionData.length > 1 ? versionData[1] : null;
}

/**
 * Get changes since the last version
 * Returns the current version's changes if available
 */
export function getChangesSinceLastVersion(): VersionEntry | null {
  return getCurrentVersion();
}

/**
 * Get a specific version entry by version string
 */
export function getVersionEntry(version: string): VersionEntry | null {
  return versionData.find(entry => entry.version === version) || null;
}
