/**
 * Version Data
 * 
 * ⚠️ AUTO-GENERATED: This file is automatically generated from packages/beacon-ui/CHANGELOG.md
 * Do not edit manually. Run `npm run sync:version` to regenerate.
 */

export interface ChangeItem {
  description: string;
}

export interface VersionEntry {
  version: string;
  date: string;
  added?: ChangeItem[];
  changed?: ChangeItem[];
  fixed?: ChangeItem[];
  deprecated?: ChangeItem[];
  removed?: ChangeItem[];
  security?: ChangeItem[];
}

const versionData: VersionEntry[] = [
  {
    "version": "3.4.3",
    "date": "2026-01-04",
    "added": [
      {
        "description": "Tabs component with Tab and TabItem subcomponents for navigation and content organization"
      },
      {
        "description": "TabItem supports horizontal and vertical placement, default and pill styles, multiple sizes, and icon support"
      },
      {
        "description": "Tab component supports equal width distribution and configurable corner radius for pill style"
      }
    ]
  },
  {
    "version": "3.4.2",
    "date": "2026-01-03",
    "added": [
      {
        "description": "Added `underline` prop to Button component for link variant to control text decoration"
      }
    ]
  },
  {
    "version": "3.4.1",
    "date": "2026-01-03",
    "changed": [
      {
        "description": "Refactored inline CSS styles in changelog, how-to-use, and releases pages to use design system token variables and CSS utility classes"
      },
      {
        "description": "Added CSS utility classes for common content patterns: `.ds-content__grid`, `.ds-content__card`, `.ds-content__flex`, `.ds-content__flex-wrap`, `.ds-content__version-badge`, `.ds-content__entry`, `.ds-content__code-container`, `.ds-content__code-wrapper`"
      }
    ],
    "fixed": [
      {
        "description": "Fixed copy button vertical alignment in code blocks for install package sections"
      },
      {
        "description": "Fixed button outline appearing momentarily on click - outline now only appears for keyboard navigation, not mouse clicks"
      },
      {
        "description": "Improved consistency of styling across documentation pages by replacing inline styles with design system classes"
      }
    ]
  },
  {
    "version": "3.4.0",
    "date": "2026-01-02",
    "added": [
      {
        "description": "Button Icon component for icon-only button interactions with support for all button variants, sizes, and states"
      },
      {
        "description": "Motion animations system with comprehensive animation library including:"
      },
      {
        "description": "Professional animations (lift, shadow depth, border glow, smooth scale)"
      },
      {
        "description": "Playful animations (bounce, elastic, jelly, pop)"
      },
      {
        "description": "Minimal animations (fade, shift, soft glow, border fade)"
      },
      {
        "description": "3D-focused animations (tilt, flip, parallax, depth glow)"
      },
      {
        "description": "Motion guide documentation with usage guidelines, best practices, and implementation examples"
      },
      {
        "description": "Icons are now available for search in design system website"
      }
    ]
  },
  {
    "version": "3.3.1",
    "date": "2026-01-01",
    "fixed": [
      {
        "description": "Fixed Card component default background color from `bg-page-tertiary` to `bg-page-secondary`"
      },
      {
        "description": "Fixed card preview elements in documentation to use `bg-page-secondary` instead of `bg-page-tertiary`"
      },
      {
        "description": "Corrected API documentation to reflect correct default background color (`page-secondary` instead of `page-tertiary`)"
      },
      {
        "description": "Fixed incorrect default values in API reference table (`showBgPattern` and `showOverlay` now correctly show `false`)"
      }
    ]
  },
  {
    "version": "3.3.0",
    "date": "2025-01-02",
    "added": [
      {
        "description": "Typography implementation guide section in documentation with code examples and best practices"
      },
      {
        "description": "Comprehensive usage examples for typography classes with copy-to-clipboard functionality"
      },
      {
        "description": "Implementation patterns for combining typography classes with inline styles for color and spacing"
      }
    ],
    "changed": [
      {
        "description": "Refactored all inline typography styles to use typography utility classes throughout documentation"
      },
      {
        "description": "Improved typography class usage consistency across all component examples"
      },
      {
        "description": "Updated build script to correctly determine font weight prefix based on fontWeight reference (not just fontFamily)"
      },
      {
        "description": "Typography classes now properly handle H3 (secondary-semibold) and H6 (secondary-medium) font weights"
      }
    ],
    "fixed": [
      {
        "description": "Fixed H3 typography class to use `font-weight-secondary-semibold` instead of `font-weight-primary-semibold`"
      },
      {
        "description": "Fixed H6 typography class to use `font-weight-secondary-medium` instead of `font-weight-secondary-semibold`"
      },
      {
        "description": "Corrected font weight determination logic in token build script to check fontWeight reference directly"
      }
    ]
  },
  {
    "version": "3.2.0",
    "date": "2025-01-01",
    "changed": [
      {
        "description": "Simplified Card component usage examples for better developer experience"
      },
      {
        "description": "Removed unnecessary wrapper divs from Card examples - Card's built-in flex layout handles spacing automatically"
      },
      {
        "description": "Improved code examples to be cleaner and more minimal, following design system best practices"
      },
      {
        "description": "Card examples now demonstrate cleaner, more maintainable code patterns"
      }
    ],
    "fixed": [
      {
        "description": "Fixed missing line-height in typography previews across Card component examples"
      },
      {
        "description": "Fixed image constraints in Product Card Pattern example - removed fixed width/height props for better flexibility"
      }
    ]
  },
  {
    "version": "3.1.9",
    "date": "2025-12-29",
    "added": [
      {
        "description": "Menu component now supports render props for full customization:"
      },
      {
        "description": "`renderSwitch` - Customize or replace the Switch component with your own implementation"
      },
      {
        "description": "`renderToggleButton` - Customize or replace the toggle button (menu/close icon) with your own component"
      },
      {
        "description": "`renderButton` - Customize or replace the menu action button with your own component"
      },
      {
        "description": "Menu component callback props for handling interactions:"
      },
      {
        "description": "`onSwitchChange` - Callback when Switch value changes"
      },
      {
        "description": "`onToggleButtonClick` - Callback when toggle button is clicked"
      },
      {
        "description": "`onButtonClick` - Callback when menu action button is clicked"
      },
      {
        "description": "Exported render prop types: `SwitchRenderProps`, `ToggleButtonRenderProps`, `MenuButtonRenderProps`"
      }
    ],
    "changed": [
      {
        "description": "Menu component now uses internal state management for Switch, allowing better control and customization"
      },
      {
        "description": "Render props are optional - if not provided, Menu uses default components (backward compatible)"
      }
    ]
  },
  {
    "version": "3.1.8",
    "date": "2025-12-29",
    "fixed": [
      {
        "description": "Button component now preserves variant colors (success, critical, warning) when in loading state"
      },
      {
        "description": "Previously, buttons would revert to default/primary color when loading was enabled"
      },
      {
        "description": "Loading state no longer overrides variant-specific colors"
      }
    ]
  },
  {
    "version": "3.1.7",
    "date": "2025-12-29",
    "changed": [
      {
        "description": "Menu component desktop variant now uses `height: \"100%\"` by default to fill container height instead of fixed `600px`"
      },
      {
        "description": "Custom height can still be set via the `style` prop to override the default behavior"
      }
    ]
  },
  {
    "version": "3.1.6",
    "date": "2025-12-29",
    "added": [
      {
        "description": "Optional `state` prop to Button component for controlled state management (default, hovered, focused, pressed)"
      },
      {
        "description": "Optional `status` prop to Switch, Checkbox, and RadioButton components for controlled state management"
      },
      {
        "description": "Components now support both controlled (via props) and uncontrolled (internal state) modes"
      },
      {
        "description": "Exported status/state types: `ButtonState`, `SwitchStatus`, `CheckboxStatus`, `RadioButtonStatus`"
      }
    ],
    "fixed": [
      {
        "description": "Menu component now uses public `Switch` component API instead of internal `SwitchPreview`"
      },
      {
        "description": "Menu component accepts optional `avatarImageUrl` prop instead of hardcoded image path"
      },
      {
        "description": "Menu component properly uses theme context for theme and hue values"
      },
      {
        "description": "Fixed nested button hydration error in Switch component wrapper"
      }
    ],
    "changed": [
      {
        "description": "Menu component falls back to `UserPersonIcon` when `avatarImageUrl` is not provided"
      },
      {
        "description": "Button, Switch, Checkbox, and RadioButton components now only update internal state when status/state prop is not provided (controlled pattern)"
      }
    ]
  },
  {
    "version": "3.1.5",
    "date": "2025-12-29",
    "fixed": [
      {
        "description": "Menu component now uses public `Switch` component API instead of internal `SwitchPreview`"
      },
      {
        "description": "Menu component accepts optional `avatarImageUrl` prop instead of hardcoded image path"
      },
      {
        "description": "Menu component properly uses theme context for theme and hue values"
      }
    ],
    "changed": [
      {
        "description": "Menu component falls back to `UserPersonIcon` when `avatarImageUrl` is not provided"
      }
    ]
  },
  {
    "version": "3.1.4",
    "date": "2025-12-29",
    "added": [
      {
        "description": "Initial npm package release as `beacon-ui`"
      },
      {
        "description": "README.md with installation and usage instructions"
      },
      {
        "description": "CHANGELOG.md for version tracking"
      },
      {
        "description": "Comprehensive documentation for all components"
      },
      {
        "description": "TypeScript type exports for design tokens"
      },
      {
        "description": "9 production-ready components:"
      },
      {
        "description": "Avatar"
      },
      {
        "description": "Button"
      },
      {
        "description": "Card"
      },
      {
        "description": "Checkbox"
      },
      {
        "description": "Chip"
      },
      {
        "description": "Input"
      },
      {
        "description": "Menu"
      },
      {
        "description": "Radio Button"
      },
      {
        "description": "Switch"
      },
      {
        "description": "ThemeProvider for theme and hue management"
      },
      {
        "description": "Complete design token system:"
      },
      {
        "description": "Primitives (colors, spacing, typography)"
      },
      {
        "description": "Semantic tokens (primary, success, warning, critical)"
      },
      {
        "description": "Brand tokens (light/dark themes)"
      },
      {
        "description": "Responsive tokens (desktop, tablet, mobile)"
      },
      {
        "description": "Effect tokens (shadows)"
      },
      {
        "description": "Typography tokens"
      },
      {
        "description": "TypeScript support with full type definitions"
      },
      {
        "description": "Icon component library"
      },
      {
        "description": "Support for multiple themes (light/dark)"
      },
      {
        "description": "Support for multiple hue variants (chromatic-prime, hue-sky, hue-indigo)"
      },
      {
        "description": "Token-driven architecture"
      },
      {
        "description": "WCAG 2.1 AA accessibility compliance"
      },
      {
        "description": "Responsive design support"
      },
      {
        "description": "Full TypeScript support"
      },
      {
        "description": "React 18 and 19 compatibility"
      }
    ]
  }
];

/**
 * Get all version entries (newest first)
 */
export function getVersionHistory(): VersionEntry[] {
  return versionData;
}

/**
 * Get the current (latest) version entry
 */
export function getCurrentVersion(): VersionEntry | null {
  return versionData.length > 0 ? versionData[0] : null;
}

/**
 * Get the previous version entry
 */
export function getPreviousVersion(): VersionEntry | null {
  return versionData.length > 1 ? versionData[1] : null;
}

/**
 * Get changes since the last version
 * Returns the current version's changes if available
 */
export function getChangesSinceLastVersion(): VersionEntry | null {
  return getCurrentVersion();
}

/**
 * Get a specific version entry by version string
 */
export function getVersionEntry(version: string): VersionEntry | null {
  return versionData.find(entry => entry.version === version) || null;
}
